-- MySQL Script generated by MySQL Workbench
-- Mon Apr 30 00:29:01 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema cst247
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cst247
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cst247` DEFAULT CHARACTER SET latin1 ;
USE `cst247` ;

-- -----------------------------------------------------
-- Table `cst247`.`ms_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cst247`.`ms_user` (
  `UserId` INT(11) NOT NULL,
  `UserFirstName` VARCHAR(45) NOT NULL,
  `UserLastName` VARCHAR(45) NOT NULL,
  `UserSex` VARCHAR(45) NOT NULL,
  `UserBirth` VARCHAR(45) NOT NULL,
  `UserState` VARCHAR(45) NOT NULL,
  `UserEmail` VARCHAR(45) NOT NULL,
  `UserUsername` VARCHAR(45) NOT NULL,
  `UserPassword` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`UserId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `cst247`.`ms_savegames`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cst247`.`ms_savegames` (
  `Id` INT(11) NOT NULL,
  `UserID` INT(11) NOT NULL,
  `GameData` VARCHAR(5000) NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `SG_UserID_idx` (`UserID` ASC),
  CONSTRAINT `SG_UserID`
    FOREIGN KEY (`UserID`)
    REFERENCES `cst247`.`ms_user` (`UserId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `cst247`.`ms_wins`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cst247`.`ms_wins` (
  `Id` INT(11) NOT NULL,
  `UserID` INT(11) NOT NULL,
  `Clicks` INT(11) NOT NULL,
  `WinDate` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `W_UserID_idx` (`UserID` ASC),
  CONSTRAINT `W_UserID`
    FOREIGN KEY (`UserID`)
    REFERENCES `cst247`.`ms_user` (`UserId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
